### ISSUE TITLE
2020年的春节前后的数据获取有一些问题

### ISSUE THREAD

**Issue by simonwang1106** [NateScarlet/holiday-cn#135]
2020年获取到的json   2020年的春节 从1月24一直到2月2号都是春节了

**Comment by simonwang1106** [comment]
是我唐突了，忘记了延长假期的通知（刚看到这个通知），从日历上看不出来

**Comment by NateScarlet** [comment]
papers 里面为官方文件地址

**Comment by simonwang1106** [comment]
好的，谢谢，我也是刚刚查到了，才发现延长的那个文件



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月22日 17:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NateScarlet/holiday-cn] 2020年的春节前后的数据获取有一些问题 (Issue #135) |

papers 里面为官方文件地址

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
