### ISSUE TITLE
镜像 url 好像用不了了

### ISSUE THREAD

**Issue by kkHAIKE** [NateScarlet/holiday-cn#163]
https://natescarlet.coding.net/p/github/d/holiday-cn/git/raw/master/2022.json

返回
{"msg":{"user_not_login":"用户未登录"},"data":{"account_type":"0"},"code":1000}

**Comment by NateScarlet** [comment]
应该是 coding 变更了功能 不能不登录直接下载单个文件了

克隆应该还是可以

**Comment by NateScarlet** [comment]
coding 废了 现在好像国内的都不能不登录下载文件了

用 ghproxy 吧

https://ghproxy.com/https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/2022.json
