### ISSUE TITLE
2024 年元旦解析有问题

### ISSUE THREAD

**Issue by anhao** [NateScarlet/holiday-cn#213]
**一、元旦：1月1日放假，与周末连休。**

2023-12-30 到 2024-1-1 放假

**Comment by NateScarlet** [comment]
2023-12-30 又不是周末 你怎么理解出这天放假的？

**Comment by anhao** [comment]
是的哈
![image](https://github.com/NateScarlet/holiday-cn/assets/9844218/d3d19f02-0b1d-4aff-a014-f61b6a060e11)
![image](https://github.com/NateScarlet/holiday-cn/assets/9844218/ee004fc8-4d9b-405d-bf5f-684c43fa8aae)

**Comment by NateScarlet** [comment]
哦 我看成11月30日了

周末本来就放假 不需要特殊表明 只有周末上班才会记录在数据里

**Comment by qilin7** [comment]
2023-12-30和31，周六或周末也有排班的，如果数据里没有特别记录为放假的话，默认就上班了。。。

**Comment by NateScarlet** [comment]
> 2023-12-30和31，周六或周末也有排班的，如果数据里没有特别记录为放假的话，默认就上班了。。。

周末为什么会默认上班 这是你那边的问题吧

**Comment by NateScarlet** [comment]
`与周末连休` 的周末不算法定节日 不然每年法定节日天数都不一样了
周末本来就是法定休息日 如果只有和法定节日相连的休息日休息 那属于自订的制度 不应该在这个库里体现
@qilin7

**Comment by qilin7** [comment]
翻了一下前几年的数据，这两年的元旦都是和周末连着的，搞的我以为元旦是三天假了。。。
