### ISSUE TITLE
错误信息，2024年端午节放假显示只有6月10号一天

### ISSUE THREAD

**Issue by MemoryHope** [NateScarlet/holiday-cn#221]
应该是8,9,10三天显示

**Comment by NateScarlet** [comment]
端午节本来就是一天

与节日连休的周末不算节日 没有三倍工资的

**Comment by NateScarlet** [comment]
更新了说明

https://github.com/NateScarlet/holiday-cn/commit/ccea60b3ce99823534ed32bb6d3b18ffb78d58fd
