### ISSUE TITLE
哥，2025的啥时候出来

### ISSUE THREAD

**Issue by Funny-dot** [NateScarlet/holiday-cn#238]
哥，2025的啥时候出来

**Comment by Jarvie789** [comment]
看看**第一句话**写的啥，再看看**注意事项**的**第一句话**写的啥。白嫖惯了，张口就问。
![image](https://github.com/user-attachments/assets/3548ba74-f9a5-4a50-b7f3-7d23d2170260)

<img width="859" alt="image" src="https://github.com/user-attachments/assets/4ad14adf-62eb-469a-a436-83d66efff502">

<img width="851" alt="image" src="https://github.com/user-attachments/assets/dc465132-80ee-47c9-9068-da826f844c54">

**Comment by NateScarlet** [comment]
取决于国务院公布的时间
