### ISSUE TITLE
是否考虑支持 ics 格式的输出

### ISSUE THREAD

**Issue by alswl** [NateScarlet/holiday-cn#33]
是否考虑支持 ics 格式的输出，方便手机 / PC 用户直接订阅。

**Comment by NateScarlet** [comment]
我没用过这个格式 欢迎PR

**Comment by alswl** [comment]
格式信息如下：https://en.wikipedia.org/wiki/ICalendar#Events_(VEVENT)

**Comment by Secbone** [comment]
@alswl  我基于这个项目做了一个 iCalendar 的订阅服务，可以看一下是不是你想要的~ 
[Secbone/calendar](https://github.com/Secbone/calendar)

**Comment by alswl** [comment]
> @alswl 我基于这个项目做了一个 iCalendar 的订阅服务，可以看一下是不是你想要的~
> [Secbone/calendar](https://github.com/Secbone/calendar)

Cool.
