### ISSUE TITLE
2020-01-31 没有哦

### ISSUE THREAD

**Issue by HugoPresents** [NateScarlet/holiday-cn#73]
https://github.com/NateScarlet/holiday-cn/blob/8a74a761c83464b51186a1fb575a20bed29eef37/2020.json#L50-L59

**Comment by NateScarlet** [comment]
哦 你是说漏了31日

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/holiday-cn/releases/tag/2020.09.07
